db:  
  container_name: recruitment-db
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: recruitment_development 
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
   - ./db:/var/lib/mysql
proxy:
  container_name: recruitment-proxy
  image: nginx:1.9.9
  volumes:
   - ./proxy/html:/usr/share/nginx/html:ro
   - ./proxy/site:/etc/nginx/sites-enabled/site:ro
   - ./app/tmp/sockets/puma.sock:/tmp/docker.sock:ro
app:
  container_name: recruitment-app
  build: app
  ports:
   - 3000:3000
  volumes:
   - ./app:/code
   - /projects/.ssh/id_rsa:/config/.ssh/id_rsa
   - /projects/.ssh/id_rsa.pub:/config/.ssh/id_rsa.pub
   - /projects/.ssh/known_hosts:/config/.ssh/known_hosts
   - /projects/.gitconfig:/config/.gitconfig
   - /projects/.atom:/config/.atom
   - /projects/atom:/config/atom
  environment:
    DISPLAY: 192.168.99.1:0.0
  links:
   - db
   - proxy
