version: '2'
services:
  mysql: 
    container_name: PROJECT-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: PROJECT_development
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./db/interview:/var/lib/mysql
  proxy:
    container_name: PROJECT-proxy
    image: nginx:1.9.9
    volumes:
      - ./proxy/html:/usr/share/nginx/html:ro
      - ./proxy/site:/etc/nginx/sites-enabled/site:ro
      - ./code/tmp/sockets/puma.sock:/tmp/docker.sock:ro
  data:
    container_name: PROJECT-data
    image: debian:jessie
    volumes:
      - code-volume:/code
      - node-modules-volume:/usr/local/lib/node_modules
      - bundle-volume:/usr/local/bundle
  node:
    container_name: PROJECT-node
    build: node
    volumes_from:
      - data
    volumes:
      - ~/.ssh:/home/dev/.ssh
    command: 'bash -c "/home/dev/run.sh; npm"'
  app:
    container_name: PROJECT-app
    build: app
    ports:
      - 3000:3000
    volumes_from:
      - data
    volumes:
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/home/dev/.gitconfig
    links:
      - mysql
      - proxy
volumes:
  code-volume:
    driver: local
  bundle-volume:
    driver: local
  node-modules-volume:
    driver: local
