db:  
  container_name: PROJECT_NAME-db
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: PROJECT_NAME_development
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
   - ./db:/var/lib/mysql
proxy:
  container_name: PROJECT_NAME-proxy
  image: nginx:1.9.9
  volumes:
   - ./proxy/html:/usr/share/nginx/html:ro
   - ./proxy/site:/etc/nginx/sites-enabled/site:ro
   - ./app/tmp/sockets/puma.sock:/tmp/docker.sock:ro
app:
  container_name: PROJECT_NAME-app
  build: app
  ports:
   - 3000:3000
  volumes:
   - ./app:/app
   - ~/.ssh:/config/.ssh/
   - ~/.gitconfig:/config/.gitconfig
   - ./utils/.gems:/config/.gems
  links:
   - db
   - proxy
