version: '2'
services:
  dev:
    container_name: PROJECT-dev
    build: dev
    volumes_from:
      - data
    volumes:
      - /boxes/atom:/home/dev/atom
      - /boxes/.atom:/home/dev/.atom
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/home/dev/.gitconfig
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: :0
    ports:
      - 3000:3000
    links:
      - mysql
