FROM ubuntu:14.04

MAINTAINER Teanoon Celord <anticipationvu@gmail.com>
LABEL Description = "base image for development purpose which allows ides"

# fix display for multiple languages
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

COPY sources.list.aliyun /etc/apt/sources.list
RUN rm -rf /var/lib/apt/lists/* && apt-get clean && \
    apt-get update && apt-get install -y --no-install-recommends \
    # common dev tools
    vim htop vim git openssh-client zsh tmux wget curl w3m \
    # common x11 client dependencies
    libdbusmenu-glib4 libdbusmenu-gtk4 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libstartup-notification0 libxcb-util0 libgconf-2-4 \
    # atom dependencies
    libnss3 libasound2 libxtst6 \
    # better fonts
    ttf-wqy-microhei \
    # certificate
    ca-certificates \
    # some ides need machine-id info like atom/eclipse
    zenity dbus && dbus-uuidgen > /etc/machine-id
    # rm -rf /var/lib/apt/lists/*
